# Generated by Django 3.0.2 on 2021-05-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charts', '0001_initial'),
        ('entities', '0001_initial'),
        ('userProfiles', '0002_userprofile_favorite_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('pending', models.BooleanField(default=False)),
                ('chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_histories', to='charts.Chart')),
                ('creating_action', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='affected_entities', to='entityHistories.EntityHistory')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_actions', to='userProfiles.UserProfile')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_histories', to='entities.Entity')),
            ],
        ),
    ]
