# Generated by Django 3.0.2 on 2021-05-04 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_remove_entity_charts'),
        ('charts', '0001_initial'),
        ('entityHistories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('temp_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_histories', to='charts.Chart')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entity_histories', to='entities.Entity')),
            ],
        ),
        migrations.DeleteModel(
            name='EntityLog',
        ),
    ]
