# Generated by Django 3.0.2 on 2021-05-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0001_initial'),
        ('entityHistories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entity_actions', to='userProfiles.UserProfile'),
        ),
    ]
