# Generated by Django 3.0.2 on 2021-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entityHistories', '0002_auto_20210504_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityhistory',
            name='temp_id',
        ),
        migrations.AddField(
            model_name='entityhistory',
            name='affected_entities',
            field=models.TextField(blank=True),
        ),
    ]
