# Generated by Django 3.0.2 on 2021-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entityHistories', '0002_auto_20210513_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='changed_legal_form',
            field=models.CharField(default='', max_length=50),
        ),
    ]
