# Generated by Django 3.0.2 on 2021-05-04 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('entityHistories', '0003_auto_20210504_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_histories', to='charts.Chart'),
        ),
    ]
