# Generated by Django 3.0.2 on 2021-05-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entityHistories', '0003_entityhistory_changed_legal_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='changed_legal_form',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
