# Generated by Django 3.0.2 on 2021-05-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entityHistories', '0004_auto_20210506_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityhistory',
            name='action',
            field=models.CharField(max_length=200),
        ),
    ]
