# Generated by Django 3.0.2 on 2021-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entityHistories', '0005_auto_20210506_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityhistory',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
