# Generated by Django 2.2.2 on 2019-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='timestamp',
            new_name='date_joined',
        ),
    ]
