version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - ./envs/dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/django-social-media:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: "tail -f /dev/null"
    ports:
      - '8000:8000'
      - '4777:22'
    depends_on:
      - postgres
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    tty: true

  email:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/django-social-media:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'python manage.py send_mail'
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    depends_on:
      - postgres
      - backend


  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  celery:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/django-social-media:latest
    restart: always
    env_file:
      - ./envs/dev.env
    command: 'celery -A app worker -l info'
    volumes:
      - ./backend:/backend
      - ./media-files:/media-files
      - ./static-files:/static-files
    depends_on:
      - postgres
      - backend
      - redis

#  flower:
#    image: mher/flower:latest
#    environment:
#      FLOWER_BROKER: "redis://redis:6379"
#      FLOWER_URL_PREFIX: "flower"
#    ports:
#      - 5555:5555
#    depends_on:
#      - redis
#      - celery

volumes:
  postgres:
  redis_data:
  media-files:
  static-files:
