version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/django-drf-template:master
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/run.sh"
    depends_on:
      - postgres
    volumes:
      - media-files:/media-files
      - static-files:/static-files

  email:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/templates/django-drf-template:master
    restart: always
    env_file:
      - ./envs/prod.env
    command: 'python manage.py send_mail'
    depends_on:
      - postgres
      - backend
    volumes:
      - media-files:/media-files
      - static-files:/static-files

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static-files:/static-files
      - media-files:/media-files
      - /etc/letsencrypt:/etc/letsencrypt



volumes:
  postgres:
  static-files:
  media-files:

