version: '3'

services:
  postgres:
    image: postgres:12
    env_file:
      - ./envs/prod.env
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/clients/stark/stark-backend:latest
    env_file:
      - ./envs/prod.env
    command: "sh /scripts/run.sh"
    depends_on:
      - postgres
    volumes:
      - media-files:/media-files
      - static-files:/static-files

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

  celery:
    image: registry.gitlab.propulsion-home.ch/propulsion/projects/clients/stark/stark-backend:latest
    restart: always
    env_file:
      - ./envs/prod.env
    command: 'celery -A app worker -l info'
    volumes:
      - media-files:/media-files
      - static-files:/static-files
    depends_on:
      - postgres
      - backend
      - redis

volumes:
  postgres:
  redis_data:
  static-files:
    external: true
  media-files:
    external: true

networks:
  default:
    external:
      name: templates-network

