name: backend

dependencies:
  - python=3.7
  - pip
  - psycopg2
  - pip:
    - Django==3.0.2
    - djangorestframework==3.11.0
    - djangorestframework_simplejwt==4.4.0
    - flake8
    - drf_yasg
    - Pillow
    - django-cors-headers
    - django-admin-honeypot
    - django-extensions
    - celery
    - redis
    - flower
    - django-celery-results
    - sentry-sdk==0.14.1
    - gunicorn

