# Generated by Django 2.2.2 on 2019-11-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='to',
            field=models.EmailField(max_length=254, verbose_name='To'),
        ),
    ]
