# Generated by Django 3.0.2 on 2020-01-23 14:16

from django.db import migrations


def populate_db(apps, schema_editor):
    # Dev Emails
    dev_emails = ['danieler@propulsionacademy.com', 'rahjen@gmail.com', 'josephedwingill@gmail.com']
    DevEmail = apps.get_model('emails', 'DevEmails')
    for email in dev_emails:
        DevEmail(email=email).save()

    # Email Types
    email_types = [
        {
            "key": "registration_email",
            "subject": "Subject: Thank you for registering!",
            "title": "Title: Thank you for registering!",
            "template": "Click <a href='{{ base_url }}registration-validation?code={{code}}&email={{email_to}}'> here</a> to finalize registration."
        },
        {
            "key": "password_reset_email",
            "subject": "Subject: Password reset",
            "title": "Title: Password reset",
            "template": "Click <a href='{{ base_url }}password-reset-validation?code={{code}}&email={{email_to}}'>  here</a> to reset your password."
        },
        {
            "key": "added_to_group",
            "subject": "Subject: You have been added to a new Group",
            "title": "Title: You have been added to a new Group",
            "template": "You have been added to a new Group."
        },
        {
            "key": "user_assigned_task",
            "subject": "Subject: You have been assigned a new Task",
            "title": "Title: You have been assigned a new Task",
            "template": "You have been assigned a new Task."
        }
    ]
    EmailType = apps.get_model('emails', 'EmailType')
    for email_type in email_types:
        EmailType(**email_type).save()




class Migration(migrations.Migration):
    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
