# Generated by Django 3.0.2 on 2020-01-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emailtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='content',
        ),
        migrations.RemoveField(
            model_name='emailtype',
            name='description',
        ),
    ]
