# Generated by Django 3.0.2 on 2020-05-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtype',
            name='key',
            field=models.CharField(max_length=200, unique=True, verbose_name='email key'),
        ),
    ]
