# Generated by Django 3.0.2 on 2020-11-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20200717_0946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'get_latest_by': 'modified'},
        ),
    ]
