# Generated by Django 3.0.2 on 2020-07-17 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20200713_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationprofile',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
