# Generated by Django 3.0.2 on 2021-01-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxConsequences', '0002_auto_20201229_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconsequence',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxconsequence',
            name='location',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
