# Generated by Django 3.0.2 on 2021-01-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxConsequences', '0003_auto_20210104_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconsequence',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
