# Generated by Django 3.0.2 on 2021-01-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_userprofile_country'),
        ('taxConsequences', '0004_auto_20210111_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxconsequence',
            name='editing_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_tax_consequences', to='userProfiles.UserProfile'),
        ),
    ]
