# Generated by Django 3.0.2 on 2021-04-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectRoles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrole',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
