# Generated by Django 3.0.2 on 2021-01-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210106_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='Not Started', max_length=15),
        ),
    ]
