# Generated by Django 3.0.2 on 2021-05-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('entities', '0002_auto_20210121_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='charts.Chart'),
        ),
    ]
