# Generated by Django 3.0.2 on 2021-05-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
        ('entities', '0003_entity_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='chart',
        ),
        migrations.AddField(
            model_name='entity',
            name='charts',
            field=models.ManyToManyField(blank=True, null=True, related_name='entities', to='charts.Chart'),
        ),
    ]
