# Generated by Django 3.0.2 on 2021-05-03 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20210503_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='charts',
        ),
    ]
