# Generated by Django 3.0.2 on 2021-05-04 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_remove_entity_charts'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
