# Generated by Django 3.0.2 on 2020-07-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200317_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialprofile',
            options={'get_latest_by': 'modified'},
        ),
        migrations.RenameField(
            model_name='socialprofile',
            old_name='avatar',
            new_name='upload_avatar',
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='social_avatar',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
