# Generated by Django 2.2.2 on 2019-11-04 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0002_auto_20191104_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('avatar', models.ImageField(blank=True, upload_to='')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='user location')),
                ('about_me', models.CharField(blank=True, max_length=1000, verbose_name='user description')),
                ('job', models.CharField(blank=True, max_length=200, verbose_name='job title')),
                ('followees', models.ManyToManyField(blank=True, related_name='followers', to='social.SocialProfile', verbose_name='followees')),
                ('liked_posts', models.ManyToManyField(blank=True, related_name='liked_by', to='social.Post', verbose_name='liked posts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
