# Generated by Django 2.2.2 on 2019-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_friend'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={},
        ),
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='status'),
        ),
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together={('requester', 'receiver')},
        ),
    ]
