# Generated by Django 2.2.2 on 2019-11-04 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20191104_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='social_profile',
        ),
    ]
