# Generated by Django 3.0.2 on 2021-05-03 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0005_auto_20210503_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakehold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_ownership', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholds_child', to='entities.Entity')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholds_parent', to='entities.Entity')),
            ],
        ),
    ]
