# Generated by Django 3.0.2 on 2021-01-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskDocuments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdocument',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
