# Generated by Django 3.0.2 on 2020-01-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtypes',
            name='template',
            field=models.CharField(default='mail_base.html', max_length=200, verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='notificationprofile',
            name='subscribed_notification_types',
            field=models.ManyToManyField(blank=True, related_name='subscribed_user_notification_profiles', to='notifications.NotificationTypes', verbose_name='subscribed notification types'),
        ),
    ]
