# Generated by Django 3.0.2 on 2020-01-15 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20200109_1553'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationTypes',
            new_name='NotificationType',
        ),
    ]
