# Generated by Django 3.0.2 on 2020-01-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20200115_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='subject'),
            preserve_default=False,
        ),
    ]
