# Generated by Django 3.0.2 on 2020-01-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtype_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='template',
            field=models.TextField(default="{% extends 'mail_base.html' %} \n {% block extension %} \n {% endblock %}", verbose_name='template name'),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
    ]
