# Generated by Django 3.0.2 on 2020-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_auto_20200115_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='template',
            field=models.TextField(verbose_name='template extension'),
        ),
    ]
