# Generated by Django 3.0.2 on 2021-05-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('userProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_groups',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='groups.Group'),
        ),
    ]
