# Generated by Django 3.0.2 on 2021-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfiles', '0002_userprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Switzerland', max_length=100),
            preserve_default=False,
        ),
    ]
